CREATE OR REPLACE TABLE GOLD_AGG_DAILY_BOOKING AS
SELECT
    check_in_date AS date,
    COUNT(*) AS total_bookings,
    SUM(total_amount) AS total_revenue
FROM SILVER_HOTEL_BOOKING
GROUP BY check_in_date;

CREATE OR REPLACE TABLE GOLD_AGG_HOTEL_CITY_SALES AS
SELECT
    hotel_city,
    SUM(total_amount) AS total_revenue
FROM SILVER_HOTEL_BOOKING
GROUP BY hotel_city;

CREATE OR REPLACE TABLE GOLD_HOTEL_BOOKING AS
SELECT *
FROM SILVER_HOTEL_BOOKING;
